import { WardrobeItem } from '../types/fashion.js';

export const INITIAL_WARDROBE: WardrobeItem[] = [
  // TOPS
  {
    id: 'item-top-1',
    name: 'Crisp Poplin Oxford Shirt',
    category: 'top',
    subcategory: 'oxford_shirt',
    primaryColor: { name: 'Optic White', hex: '#FFFFFF', temperature: 'neutral' },
    accentColors: ['#F3F4F6'],
    pattern: 'solid',
    material: '100% Egyptian Cotton',
    texture: 'crisp poplin',
    fit: 'tailored',
    formalityScore: 7,
    seasonality: ['spring', 'summer', 'fall', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['essential', 'smart_casual', 'business_formal', 'layering'],
    timesWorn: 14,
    rating: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-top-2',
    name: 'Sage Camp-Collar Linen Shirt',
    category: 'top',
    subcategory: 'camp_collar_shirt',
    primaryColor: { name: 'Sage Green', hex: '#8A9A86', temperature: 'cool' },
    accentColors: ['#6B7280'],
    pattern: 'solid',
    material: 'French Linen',
    texture: 'airy slub',
    fit: 'relaxed',
    formalityScore: 4,
    seasonality: ['spring', 'summer'],
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['resort', 'vacation', 'brunch', 'casual'],
    timesWorn: 8,
    rating: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-top-3',
    name: 'Heavyweight Boxy Crewneck Tee',
    category: 'top',
    subcategory: 't_shirt',
    primaryColor: { name: 'Washed Black', hex: '#262626', temperature: 'neutral' },
    accentColors: ['#404040'],
    pattern: 'solid',
    material: '280gsm Combed Cotton',
    texture: 'matte structured',
    fit: 'oversized',
    formalityScore: 3,
    seasonality: ['spring', 'summer', 'fall', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['streetwear', 'casual', 'minimalist'],
    timesWorn: 22,
    rating: 4,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-top-4',
    name: 'Merino Wool Oatmeal Waffle Knit',
    category: 'top',
    subcategory: 'knit_sweater',
    primaryColor: { name: 'Oatmeal Melange', hex: '#D6C7B2', temperature: 'warm' },
    accentColors: ['#E5E7EB'],
    pattern: 'textured',
    material: 'Extra-Fine Merino Wool',
    texture: 'waffle knit',
    fit: 'regular',
    formalityScore: 6,
    seasonality: ['fall', 'winter', 'spring'],
    imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['quiet_luxury', 'smart_casual', 'cozy'],
    timesWorn: 11,
    rating: 5,
    createdAt: new Date().toISOString()
  },

  // BOTTOMS
  {
    id: 'item-bot-1',
    name: 'Pleated Tapered Chinos',
    category: 'bottom',
    subcategory: 'pleated_trousers',
    primaryColor: { name: 'Midnight Navy', hex: '#1B263B', temperature: 'cool' },
    accentColors: ['#0D1B2A'],
    pattern: 'solid',
    material: 'Cotton Twill Blend',
    texture: 'smooth structured',
    fit: 'tailored',
    formalityScore: 7,
    seasonality: ['spring', 'summer', 'fall', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['office', 'date_night', 'smart_casual'],
    timesWorn: 19,
    rating: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-bot-2',
    name: 'Washed Vintage Straight-Leg Denim',
    category: 'bottom',
    subcategory: 'jeans',
    primaryColor: { name: 'Light Indigo', hex: '#6888A1', temperature: 'cool' },
    accentColors: ['#D1D5DB'],
    pattern: 'solid',
    material: '13oz Japanese Selvedge Denim',
    texture: 'slub twill',
    fit: 'regular',
    formalityScore: 3,
    seasonality: ['spring', 'summer', 'fall', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['casual', 'weekend', 'streetwear'],
    timesWorn: 27,
    rating: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-bot-3',
    name: 'Italian Wool Flannel Trousers',
    category: 'bottom',
    subcategory: 'dress_trousers',
    primaryColor: { name: 'Heather Charcoal', hex: '#374151', temperature: 'neutral' },
    accentColors: ['#1F2937'],
    pattern: 'textured',
    material: '100% Super 120s Wool',
    texture: 'soft brushed flannel',
    fit: 'tailored',
    formalityScore: 8,
    seasonality: ['fall', 'winter', 'spring'],
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['business_formal', 'evening_cocktail', 'tailored'],
    timesWorn: 9,
    rating: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-bot-4',
    name: 'Relaxed Olive Cargo Fatigue Pants',
    category: 'bottom',
    subcategory: 'cargo_pants',
    primaryColor: { name: 'Military Olive', hex: '#525B44', temperature: 'warm' },
    accentColors: ['#3A3E3B'],
    pattern: 'solid',
    material: 'Ripstop Cotton',
    texture: 'matte washed',
    fit: 'relaxed',
    formalityScore: 3,
    seasonality: ['spring', 'summer', 'fall'],
    imageUrl: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['utilitarian', 'streetwear', 'casual'],
    timesWorn: 15,
    rating: 4,
    createdAt: new Date().toISOString()
  },

  // OUTERWEAR
  {
    id: 'item-out-1',
    name: 'Unstructured Sand Linen Blazer',
    category: 'outerwear',
    subcategory: 'blazer',
    primaryColor: { name: 'Warm Sand', hex: '#D5C4A1', temperature: 'warm' },
    accentColors: ['#FFFFFF'],
    pattern: 'textured',
    material: 'Italian Linen / Silk Blend',
    texture: 'open weave',
    fit: 'regular',
    formalityScore: 8,
    seasonality: ['spring', 'summer'],
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['resort_chic', 'summer_wedding', 'smart_casual'],
    timesWorn: 6,
    rating: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-out-2',
    name: 'Camel Double-Breasted Wool Coat',
    category: 'outerwear',
    subcategory: 'overcoat',
    primaryColor: { name: 'Camel Tan', hex: '#C19A6B', temperature: 'warm' },
    accentColors: ['#8B5A2B'],
    pattern: 'solid',
    material: 'Melton Wool & Cashmere',
    texture: 'plush felted',
    fit: 'tailored',
    formalityScore: 9,
    seasonality: ['fall', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['statement', 'cold_weather', 'timeless'],
    timesWorn: 12,
    rating: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-out-3',
    name: 'Type III Raw Denim Trucker Jacket',
    category: 'outerwear',
    subcategory: 'denim_jacket',
    primaryColor: { name: 'Deep Indigo', hex: '#1C3144', temperature: 'cool' },
    accentColors: ['#B45309'],
    pattern: 'solid',
    material: '14.5oz Raw Denim',
    texture: 'rigid twill',
    fit: 'regular',
    formalityScore: 4,
    seasonality: ['spring', 'fall'],
    imageUrl: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['heritage', 'casual', 'rugged'],
    timesWorn: 30,
    rating: 5,
    createdAt: new Date().toISOString()
  },

  // FOOTWEAR
  {
    id: 'item-shoe-1',
    name: 'Minimalist White Nappa Sneakers',
    category: 'footwear',
    subcategory: 'sneakers',
    primaryColor: { name: 'Clean White', hex: '#F9FAFB', temperature: 'neutral' },
    accentColors: ['#E5E7EB'],
    pattern: 'solid',
    material: 'Italian Full-Grain Calfskin',
    texture: 'butter smooth',
    fit: 'regular',
    formalityScore: 5,
    seasonality: ['spring', 'summer', 'fall', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['anchor', 'daily_driver', 'minimalist'],
    timesWorn: 45,
    rating: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-shoe-2',
    name: 'Tobacco Suede Chelsea Boots',
    category: 'footwear',
    subcategory: 'boots',
    primaryColor: { name: 'Tobacco Brown', hex: '#784315', temperature: 'warm' },
    accentColors: ['#1F2937'],
    pattern: 'solid',
    material: 'Reverse Calf Suede',
    texture: 'velvety nap',
    fit: 'tailored',
    formalityScore: 7,
    seasonality: ['fall', 'winter', 'spring'],
    imageUrl: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['date_night', 'elevated', 'autumn_essential'],
    timesWorn: 18,
    rating: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 'item-shoe-3',
    name: 'Penny Loafers in Polished Black Calf',
    category: 'footwear',
    subcategory: 'loafers',
    primaryColor: { name: 'Gloss Black', hex: '#111827', temperature: 'neutral' },
    accentColors: ['#374151'],
    pattern: 'solid',
    material: 'Goodyear Welted Calfskin',
    texture: 'buffed sheen',
    fit: 'tailored',
    formalityScore: 8,
    seasonality: ['spring', 'summer', 'fall'],
    imageUrl: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=600&q=80',
    versatilityTags: ['smart_casual', 'preppy', 'cocktail'],
    timesWorn: 13,
    rating: 5,
    createdAt: new Date().toISOString()
  }
];
